# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userinfo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0euserinfo.proto\"\x8d\x03\n\x0cuserResponse\x12)\n\x07\x61\x63tions\x18\x01 \x01(\x0b\x32\x18.userResponse.actionInfo\x12\'\n\x07userInf\x18\x02 \x03(\x0b\x32\x16.userResponse.userInfo\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x13\n\x0bsomeNumOut1\x18\x07 \x01(\t\x12\x13\n\x0bsomeNumOut2\x18\x08 \x01(\t\x12\x13\n\x0bsomeNumOut3\x18\t \x01(\t\x1aQ\n\nactionInfo\x12\r\n\x05tName\x18\x01 \x01(\t\x12\x10\n\x08someNum1\x18\x02 \x01(\t\x12\x10\n\x08someNum2\x18\x03 \x01(\t\x12\x10\n\x08someNum3\x18\x04 \x01(\t\x1a\x87\x01\n\x08userInfo\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x1ak\n\nuserDetail\x12\x11\n\tsomeNum11\x18\x01 \x01(\t\x12\x11\n\tsomeNum12\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x1a%\n\x03img\x12\x10\n\x08portrait\x18\x01 \x03(\t\x12\x0c\n\x04icon\x18\x02 \x01(\tb\x06proto3'
)




_USERRESPONSE_ACTIONINFO = _descriptor.Descriptor(
  name='actionInfo',
  full_name='userResponse.actionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tName', full_name='userResponse.actionInfo.tName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNum1', full_name='userResponse.actionInfo.someNum1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNum2', full_name='userResponse.actionInfo.someNum2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNum3', full_name='userResponse.actionInfo.someNum3', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=278,
)

_USERRESPONSE_USERINFO_USERDETAIL_IMG = _descriptor.Descriptor(
  name='img',
  full_name='userResponse.userInfo.userDetail.img',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='portrait', full_name='userResponse.userInfo.userDetail.img.portrait', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='userResponse.userInfo.userDetail.img.icon', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=416,
)

_USERRESPONSE_USERINFO_USERDETAIL = _descriptor.Descriptor(
  name='userDetail',
  full_name='userResponse.userInfo.userDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='someNum11', full_name='userResponse.userInfo.userDetail.someNum11', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNum12', full_name='userResponse.userInfo.userDetail.someNum12', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='userResponse.userInfo.userDetail.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERRESPONSE_USERINFO_USERDETAIL_IMG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=416,
)

_USERRESPONSE_USERINFO = _descriptor.Descriptor(
  name='userInfo',
  full_name='userResponse.userInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='userResponse.userInfo.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERRESPONSE_USERINFO_USERDETAIL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=416,
)

_USERRESPONSE = _descriptor.Descriptor(
  name='userResponse',
  full_name='userResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='userResponse.actions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInf', full_name='userResponse.userInf', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='userResponse.total', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNumOut1', full_name='userResponse.someNumOut1', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNumOut2', full_name='userResponse.someNumOut2', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someNumOut3', full_name='userResponse.someNumOut3', index=5,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERRESPONSE_ACTIONINFO, _USERRESPONSE_USERINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=416,
)

_USERRESPONSE_ACTIONINFO.containing_type = _USERRESPONSE
_USERRESPONSE_USERINFO_USERDETAIL_IMG.containing_type = _USERRESPONSE_USERINFO_USERDETAIL
_USERRESPONSE_USERINFO_USERDETAIL.containing_type = _USERRESPONSE_USERINFO
_USERRESPONSE_USERINFO.containing_type = _USERRESPONSE
_USERRESPONSE.fields_by_name['actions'].message_type = _USERRESPONSE_ACTIONINFO
_USERRESPONSE.fields_by_name['userInf'].message_type = _USERRESPONSE_USERINFO
DESCRIPTOR.message_types_by_name['userResponse'] = _USERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

userResponse = _reflection.GeneratedProtocolMessageType('userResponse', (_message.Message,), {

  'actionInfo' : _reflection.GeneratedProtocolMessageType('actionInfo', (_message.Message,), {
    'DESCRIPTOR' : _USERRESPONSE_ACTIONINFO,
    '__module__' : 'userinfo_pb2'
    # @@protoc_insertion_point(class_scope:userResponse.actionInfo)
    })
  ,

  'userInfo' : _reflection.GeneratedProtocolMessageType('userInfo', (_message.Message,), {

    'userDetail' : _reflection.GeneratedProtocolMessageType('userDetail', (_message.Message,), {

      'img' : _reflection.GeneratedProtocolMessageType('img', (_message.Message,), {
        'DESCRIPTOR' : _USERRESPONSE_USERINFO_USERDETAIL_IMG,
        '__module__' : 'userinfo_pb2'
        # @@protoc_insertion_point(class_scope:userResponse.userInfo.userDetail.img)
        })
      ,
      'DESCRIPTOR' : _USERRESPONSE_USERINFO_USERDETAIL,
      '__module__' : 'userinfo_pb2'
      # @@protoc_insertion_point(class_scope:userResponse.userInfo.userDetail)
      })
    ,
    'DESCRIPTOR' : _USERRESPONSE_USERINFO,
    '__module__' : 'userinfo_pb2'
    # @@protoc_insertion_point(class_scope:userResponse.userInfo)
    })
  ,
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:userResponse)
  })
_sym_db.RegisterMessage(userResponse)
_sym_db.RegisterMessage(userResponse.actionInfo)
_sym_db.RegisterMessage(userResponse.userInfo)
_sym_db.RegisterMessage(userResponse.userInfo.userDetail)
_sym_db.RegisterMessage(userResponse.userInfo.userDetail.img)


# @@protoc_insertion_point(module_scope)
